version: '3'
services:
  importer:
    image: folkbildning.importer:latest
    build: ./importer
    volumes:
      - /Users/Johannes/PycharmProjects/Folkbildning/importer/db:db
  web:
    image: folkbildning.web:latest
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - /Users/Johannes/PycharmProjects/Folkbildning/importer/db:/db

volumes:
  db: