version: '3.7'
services:
  importer:
    image: folkbildning.importer:latest
    restart: unless-stopped
    build: ./importer
    volumes:
      - type: bind
        source: ./db
        target: /db/
      - type: bind
        source: ./log
        target: /log/
  web:
    image: folkbildning.web:latest
    restart: unless-stopped
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - type:  bind
        source: ./db
        target: /db/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bildningstid.rule=Host(`bildningstid.se`)"
      - "traefik.http.routers.bildningstid.entrypoints=websecure"
      - "traefik.http.routers.bildningstid.tls.certresolver=myresolver"
networks:
  default:
    external: 
      name: gateway
