version: '3.7'
services:
  importer:
    image: folkbildning.importer:latest
    build: ./importer
    volumes:
      - type: bind
        source: /Users/Johannes/PycharmProjects/Folkbildning/db
        target: /importer/db/
  web:
    image: folkbildning.web:latest
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - type:  bind
        source: /Users/Johannes/PycharmProjects/Folkbildning/db
        target: /web/db/