version: '3'
services:
  importer:
    image: folkbildning.importer:latest
    build: ./importer
    volumes:
      - db:/importer/db
  web:
    image: folkbildning.web:latest
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - db:/web/db
    depends_on:
      - "importer"
volumes:
    db: